theme = "adwaita-dark"

[editor]
line-number = "relative"
auto-save = true
auto-format = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-inlay-hints = true

[editor.file-picker]
hidden = false

[editor.whitespace.render]
tab = "all"
nbsp = "all"

[keys.normal]
C-s = ":update"
C-p = "file_picker"
A-z = ":toggle soft-wrap.enable"
F5 = ":reload"

[keys.normal."'"]
f = ":format"

