[[language]]
name = "rust"
rulers = [100]

[[language]]
name = "kdl"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "markdown"
soft-wrap.enable = true

[language-server.rust-analyzer.config]
check.command = "clippy"
rustfmt.overrideCommand = ["rustfmt", "+nightly", "--edition", "2021"]
completion.callable.snippets = "add_parentheses"
diagnostics.disabled = ["inactive-code"]
