terminal.shell.program = "/usr/bin/fish"
# hints.alphabet = "ntesiroahdlpufywc.x;q/z"

general.import = [
    "~/.config/alacritty/catppuccin-mocha.toml",
    # "~/.config/alacritty/catppuccin-latte.toml",
    # "~/.config/alacritty/github_light.toml",
    # "~/.config/alacritty/adwaita_dark.toml",
    # "~/.config/alacritty/github_dark.toml",

    # "~/.config/alacritty/latency.toml",
]

[window]
# dimensions = { columns = 120, lines = 74 }
# dimensions = { columns = 300, lines = 74 }
# dimensions = { columns = 42, lines = 26 }
padding = { x = 2, y = 2 }
# padding = { x = 9, y = 14 }
# dynamic_padding = true
# opacity = 0.98
# opacity = 0.5
# opacity = 0.0
# startup_mode = "Fullscreen"

[colors]
transparent_background_colors = true

[font]
size = 10
# size = 10.5
# size = 11
# size = 12
# size = 14
# size = 16
# size = 20
# size = 30
# normal.family = "IosevkaTerm NFM Medium"
# normal.family = "Iosevka Term Medium Extended"
# normal.family = "JetBrains Mono Medium Nerd Font"
# normal.family = "Fira Code"
# builtin_box_drawing = false

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true
command = "xdg-open"
post_processing = true
binding = { key = "T", mods = "Control|Shift" }
mouse = { enabled = true, mods = "None" }

[[hints.enabled]]
regex = "[0-9a-f]{12,128}|[a-f0-9]{7,8}"
action = "Copy"
binding = { key = "H", mods = "Control|Shift" }
